services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "${HOST_PORT}${ADDR}"
    command: [ "/app" ]
    environment:
      - POSTGRES_CONNECTION_URI=postgres://user:password@postgres:5432/ajiteshcc
      - JWT_SECRET=${JWT_SECRET}
      - TOTP_SECRET=${TOTP_SECRET}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_PHOTOS_BUCKET_NAME=${R2_PHOTOS_BUCKET_NAME}
      - R2_PHOTOS_BUCKET_PUBLIC_URL=${R2_PHOTOS_BUCKET_PUBLIC_URL}
      - CERT_FILE=${CERT_FILE}
      - KEY_FILE=${KEY_FILE}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DEBUG=${DEBUG}
      - ADDR=${ADDR}
    volumes:
      - ./certs:/app/certs
    restart: unless-stopped
  postgres:
    image: postgres:14.15
    container_name: postgres
    environment:
      POSTGRES_DB: ajiteshcc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
